import type { Metadata } from "next";
import { Toaster } from 'react-hot-toast';
import NavBar from "@/components/NavBar";
import { ThemeProvider } from 'next-themes';
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NavBar />
          <main className="min-h-screen">{children}</main>
          <Toaster position="top-left"/>
        </ThemeProvider>
      </body>
    </html>
  );
}
